//! A deterministic generator for the lint TESTS, and only for them.
//!
//! The lint test modules drew their synthetic data from the engine's own
//! counter-based generator (`evolve::{draw, below, coin}`). That made fuller's
//! tests depend on the evolutionary engine, which is splitting into its own
//! crate (`docs/SPLIT_fuller_phylu.md` §5, item 1) — and fuller must not depend
//! on phylu.
//!
//! This is a copy, and deliberately a BIT-IDENTICAL one: same domain constant,
//! same SplitMix64 finaliser, same argument order. The fixtures the lint tests
//! assert against were generated by the engine's draws, so any difference here
//! would change the test data and turn a relocation into a behaviour change.
//! `the_copy_is_pinned_to_the_engines_values` pins it to golden values, and phylu's
//! engine carries the same four values in `pinned_values_shared_with_fullers_test_copy`,
//! so a change on either side fails a test on that side.
//!
//! Test-only: the production generator is the engine's, keyed for exact resume,
//! and it stays with the engine.

const DOMAIN_EVOLVE: u64 = 0x6B86_E41A_79C1_9B14;

fn mix64(mut x: u64) -> u64 {
    x ^= x >> 30;
    x = x.wrapping_mul(0xBF58_476D_1CE4_E5B9);
    x ^= x >> 27;
    x = x.wrapping_mul(0x94D0_49BB_1331_11EB);
    x ^= x >> 31;
    x
}

fn mix64_3(domain: u64, a: u64, b: u64, c: u64) -> u64 {
    mix64(mix64(mix64(domain ^ a) ^ b) ^ c)
}

/// One draw, a pure function of where it is used.
pub fn draw(seed: u32, generation: u32, row: u32, slot: u32, stream: u32) -> u64 {
    let domain = DOMAIN_EVOLVE ^ u64::from(seed) ^ (u64::from(stream) << 32);
    mix64_3(domain, u64::from(generation), u64::from(row), u64::from(slot))
}

/// A draw mapped onto `0 .. n-1` by the Lemire multiply-shift.
pub fn below(h: u64, n: u32) -> u32 {
    ((u128::from(h) * u128::from(n)) >> 64) as u32
}

/// A fair coin: the hash's top bit.
pub fn coin(h: u64) -> bool {
    h >> 63 == 1
}

#[cfg(test)]
mod tests {
    /// Golden values taken from the engine's generator. The engine now lives in
    /// phylu, which asserts the SAME four values against its own `draw`; the
    /// two copies agree because both agree with this table.
    pub(super) const PINNED: [(u32, u64, u32, bool); 4] = [
        (0, 0x13da_cd4d_bbe7_2b74, 0, false),
        (7, 0x2f95_a4e1_588a_1a11, 2, false),
        (7014, 0x680b_9c63_7c55_c7da, 4, false),
        (u32::MAX, 0x50e4_8474_118d_4460, 3, false),
    ];

    #[test]
    fn the_copy_is_pinned_to_the_engines_values() {
        for (seed, h, b, c) in PINNED {
            let got = super::draw(seed, 3, 5, 0, 5);
            assert_eq!(got, h, "draw diverged at seed {seed}");
            assert_eq!(super::below(got, 11), b);
            assert_eq!(super::coin(got), c);
        }
    }
}
