//! A deterministic generator for the lint TESTS, and only for them.
//!
//! The lint test modules drew their synthetic data from the engine's own
//! counter-based generator (`evolve::{draw, below, coin}`). That made fuller's
//! tests depend on the evolutionary engine, which is splitting into its own
//! crate (`docs/SPLIT_fuller_phylu.md` §5, item 1) — and fuller must not depend
//! on phylu.
//!
//! This is a copy, and deliberately a BIT-IDENTICAL one: same domain constant,
//! same SplitMix64 finaliser, same argument order. The fixtures the lint tests
//! assert against were generated by the engine's draws, so any difference here
//! would change the test data and turn a relocation into a behaviour change.
//! `the_copy_matches_the_engine_generator` pins it while both still exist.
//!
//! Test-only: the production generator is the engine's, keyed for exact resume,
//! and it stays with the engine.

const DOMAIN_EVOLVE: u64 = 0x6B86_E41A_79C1_9B14;

fn mix64(mut x: u64) -> u64 {
    x ^= x >> 30;
    x = x.wrapping_mul(0xBF58_476D_1CE4_E5B9);
    x ^= x >> 27;
    x = x.wrapping_mul(0x94D0_49BB_1331_11EB);
    x ^= x >> 31;
    x
}

fn mix64_3(domain: u64, a: u64, b: u64, c: u64) -> u64 {
    mix64(mix64(mix64(domain ^ a) ^ b) ^ c)
}

/// One draw, a pure function of where it is used.
pub fn draw(seed: u32, generation: u32, row: u32, slot: u32, stream: u32) -> u64 {
    let domain = DOMAIN_EVOLVE ^ u64::from(seed) ^ (u64::from(stream) << 32);
    mix64_3(domain, u64::from(generation), u64::from(row), u64::from(slot))
}

/// A draw mapped onto `0 .. n-1` by the Lemire multiply-shift.
pub fn below(h: u64, n: u32) -> u32 {
    ((u128::from(h) * u128::from(n)) >> 64) as u32
}

/// A fair coin: the hash's top bit.
pub fn coin(h: u64) -> bool {
    h >> 63 == 1
}

#[cfg(test)]
mod tests {
    /// While the engine still lives in this crate, prove the copy is exact. The
    /// test goes when the engine moves; the constants above do not change.
    #[test]
    fn the_copy_matches_the_engine_generator() {
        for seed in [0u32, 7, 7014, u32::MAX] {
            for row in 0..64u32 {
                let a = super::draw(seed, 3, row, row % 5, row % 7);
                let b = crate::evolve::draw(seed, 3, row, row % 5, row % 7);
                assert_eq!(a, b, "draw diverged at seed {seed} row {row}");
                assert_eq!(super::below(a, 11), crate::evolve::below(b, 11));
                assert_eq!(super::coin(a), crate::evolve::coin(b));
            }
        }
    }
}
