//! The WGSL kingdom's function table, read from `kingdoms/wgsl/functions.tsv`
//! (generated by `gen_tables.py`; this file never edits it). The reader uses
//! the `naga` column in reverse: given the IR node a kernel holds and the slot
//! it computes over, which `class.instance` row is it?
//!
//! Several rows share one naga node (`Binary::Add` is `arith.add`,
//! `index.add`, `count.add` and `int.add`), so the choice is by the slot's
//! scalar kind, and among rows that still tie by table order: `arith` before
//! `index` before `count` before `int`, which makes `index` the default form
//! of a `u32` and `real` of a float. Form inference by use (the plan's
//! `infer.rs`) refines that later; what is read here is the slot's default.

use std::collections::BTreeMap;

/// One template row of `functions.tsv`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Template {
    /// `F001`…
    pub reference: String,
    pub class: String,
    pub instance: String,
    /// The naga node the row reads from and writes to, as the table spells
    /// it: `Binary::Add`, `Math::Sin`, `Literal`, `composite`…
    pub naga: String,
    /// The input duals, as written (`<S.real>`, `u32.index`, …); empty for a
    /// terminal.
    pub inputs: Vec<String>,
    pub output: String,
    pub arity: usize,
    pub note: String,
}

impl Template {
    /// `class.instance`.
    pub fn name(&self) -> String {
        format!("{}.{}", self.class, self.instance)
    }

    /// Which scalar kinds the row's FIRST input admits, from its dual
    /// pattern: `real` is a float, `int` a signed integer, `index`/`count`/
    /// `bits`/`hash32`/the codes an unsigned one, `flag`/`sign` a bool; `c`
    /// (any form) admits every kind.
    pub fn admits(&self, kind: ScalarKind) -> bool {
        match self.inputs.first() {
            None => true,
            Some(pattern) => form_of(pattern).and_then(form_kind).is_none_or(|k| k == kind),
        }
    }
}

/// The scalar kind of a slot, the one fact the reader has for every node
/// before any form inference.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ScalarKind {
    Float,
    Sint,
    Uint,
    Bool,
}

/// The form a dual pattern names: `<S.real>` → `real`, `u32.index` → `index`,
/// `<vecL<f32>.real>` → `real`, `<S.c>` → `c`, `<T.form of the buffer>` → None.
pub fn form_of(pattern: &str) -> Option<&str> {
    let inner = pattern.trim_start_matches('<').trim_end_matches('>');
    let form = inner.rsplit('.').next()?;
    if form.contains(' ') {
        return None;
    }
    Some(form)
}

/// The scalar kind a form lives in, `None` for `c` (any) and the per-kernel
/// placeholders.
pub fn form_kind(form: &str) -> Option<ScalarKind> {
    Some(match form {
        "real" => ScalarKind::Float,
        "int" | "q15_16" | "q15_16w" => ScalarKind::Sint,
        "index" | "count" | "code4" | "code8" | "code16" | "code1024" | "bits" | "hash32" | "hash64" => ScalarKind::Uint,
        "flag" | "sign" => ScalarKind::Bool,
        _ => return None,
    })
}

/// Split an `in` column on spaces outside angle brackets: a pattern such as
/// `<T.form of the buffer>` carries spaces of its own.
fn split_patterns(column: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut depth = 0usize;
    for c in column.chars() {
        match c {
            '<' => {
                depth += 1;
                cur.push(c);
            }
            '>' => {
                depth = depth.saturating_sub(1);
                cur.push(c);
            }
            ' ' if depth == 0 => {
                if !cur.is_empty() {
                    out.push(std::mem::take(&mut cur));
                }
            }
            _ => cur.push(c),
        }
    }
    if !cur.is_empty() {
        out.push(cur);
    }
    out
}

/// The table, indexed by naga node name.
#[derive(Debug, Clone)]
pub struct FunctionTable {
    pub rows: Vec<Template>,
    by_naga: BTreeMap<String, Vec<usize>>,
}

impl FunctionTable {
    /// The table shipped in the crate.
    pub fn shipped() -> FunctionTable {
        FunctionTable::parse(include_str!("../../kingdoms/wgsl/functions.tsv"))
            .unwrap_or_else(|e| panic!("kingdoms/wgsl/functions.tsv does not parse: {e}"))
    }

    pub fn parse(tsv: &str) -> Result<FunctionTable, String> {
        let mut lines = tsv.lines();
        let header: Vec<&str> = lines.next().ok_or("empty table")?.split('\t').collect();
        let want = ["ref", "class", "instance", "naga", "in", "out", "arity", "note"];
        if header != want {
            return Err(format!("functions.tsv header is {header:?}, want {want:?}"));
        }
        let mut rows = Vec::new();
        let mut by_naga: BTreeMap<String, Vec<usize>> = BTreeMap::new();
        for (n, line) in lines.enumerate() {
            let f: Vec<&str> = line.split('\t').collect();
            if f.len() != 8 {
                return Err(format!("line {}: {} fields, want 8", n + 2, f.len()));
            }
            let inputs = if f[4] == "-" { Vec::new() } else { split_patterns(f[4]) };
            let arity: usize = f[6].parse().map_err(|e| format!("line {}: arity {:?}: {e}", n + 2, f[6]))?;
            if arity != inputs.len() {
                return Err(format!("line {}: arity {arity} but {} inputs", n + 2, inputs.len()));
            }
            let row = Template {
                reference: f[0].to_string(),
                class: f[1].to_string(),
                instance: f[2].to_string(),
                naga: f[3].to_string(),
                inputs,
                output: f[5].to_string(),
                arity,
                note: f[7].to_string(),
            };
            by_naga.entry(row.naga.clone()).or_default().push(rows.len());
            rows.push(row);
        }
        Ok(FunctionTable { rows, by_naga })
    }

    /// Every row that reads from `naga` (e.g. `Binary::Add`), in table order.
    pub fn rows_for(&self, naga: &str) -> Vec<&Template> {
        self.by_naga.get(naga).map(|ix| ix.iter().map(|&i| &self.rows[i]).collect()).unwrap_or_default()
    }

    /// The row for a naga node computing over a slot of scalar kind `kind`
    /// with `arity` operands: the first row in table order that reads from
    /// that node, admits the kind and takes that many operands. `None` when
    /// the table has no row, which the reader reports rather than invents.
    pub fn resolve(&self, naga: &str, kind: ScalarKind, arity: usize) -> Option<&Template> {
        self.rows_for(naga).into_iter().find(|t| t.arity == arity && t.admits(kind))
    }

    /// The row named `class.instance`.
    pub fn named(&self, name: &str) -> Option<&Template> {
        self.rows.iter().find(|t| t.name() == name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_shipped_table_has_197_templates_with_consistent_arities() {
        let t = FunctionTable::shipped();
        assert_eq!(t.rows.len(), 197);
        assert_eq!(t.rows[0].reference, "F001");
        assert_eq!(t.rows[196].reference, "F197");
        assert_eq!(t.rows.iter().map(|r| r.arity).max(), Some(3), "the widest template today is 3-ary");
        let names: std::collections::BTreeSet<String> = t.rows.iter().map(Template::name).collect();
        assert_eq!(names.len(), 197, "class.instance names are unique");
    }

    #[test]
    fn binary_add_resolves_by_scalar_kind_with_index_as_the_u32_default() {
        let t = FunctionTable::shipped();
        assert_eq!(t.resolve("Binary::Add", ScalarKind::Float, 2).unwrap().name(), "arith.add");
        assert_eq!(t.resolve("Binary::Add", ScalarKind::Uint, 2).unwrap().name(), "index.add");
        assert_eq!(t.resolve("Binary::Add", ScalarKind::Sint, 2).unwrap().name(), "int.add");
        assert_eq!(t.resolve("Binary::And", ScalarKind::Uint, 2).unwrap().name(), "bits.and");
        assert_eq!(t.resolve("Binary::LogicalAnd", ScalarKind::Bool, 2).unwrap().name(), "logic.and");
        assert_eq!(t.resolve("Math::Clamp", ScalarKind::Float, 3).unwrap().name(), "arith.clamp");
        assert_eq!(t.resolve("Math::Clamp", ScalarKind::Uint, 3).unwrap().name(), "index.clamp");
        assert_eq!(t.resolve("Select", ScalarKind::Float, 3).unwrap().name(), "select.scalar_cond");
        assert_eq!(t.resolve("Binary::Less", ScalarKind::Float, 2).unwrap().name(), "compare.lt");
        assert!(t.resolve("Binary::Add", ScalarKind::Bool, 2).is_none(), "no row adds booleans");
        assert!(t.resolve("Math::Modf", ScalarKind::Float, 1).is_none(), "modf has no row and is reported, not invented");
    }

    #[test]
    fn input_patterns_split_on_spaces_outside_angle_brackets() {
        assert_eq!(split_patterns("u32.index <T.form of the buffer>"), vec!["u32.index", "<T.form of the buffer>"]);
        assert_eq!(split_patterns("<S.real> <S.real> <S.real>").len(), 3);
        assert_eq!(split_patterns("<matCxR<f32>.real> <vecC<f32>.real>"), vec!["<matCxR<f32>.real>", "<vecC<f32>.real>"]);
    }

    #[test]
    fn form_and_kind_read_every_pattern_shape() {
        assert_eq!(form_of("<S.real>"), Some("real"));
        assert_eq!(form_of("<vecL<f32>.real>"), Some("real"));
        assert_eq!(form_of("u32.index"), Some("index"));
        assert_eq!(form_of("<S.c>"), Some("c"));
        assert_eq!(form_of("<T.form of the buffer>"), None);
        assert_eq!(form_kind("c"), None);
        assert_eq!(form_kind("bits"), Some(ScalarKind::Uint));
    }
}
